import Head from 'next/head'
import Layout from './../components/Layout'
import Container from './../components/Container'
import products from './../data/products.json'

export default function Home() {
  return (
    < Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div>
          {products.map(product => {
            return(
              <div key={product.id}>
                <h2>{product.name}</h2>
                <h3>{product.price}</h3>

              </div>
            )
          })}
        </div>
      </Container>
    </ Layout>
  )
}
