import Head from 'next/head'
import Layout from './../components/Layout'
import Container from './../components/Container'
import products from './../data/products.json'
import Link from 'next/link'

export default function Home() {
  return (
    < Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div>
          {products.map(product => {
            return(
              <div key={product.id}>
                <h2>{product.name}</h2>
                <h3>{product.price}</h3>
                <Link href={`/produits/${product.id}`}>
                  Voir le produit
                </Link>
                <button className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-image={product.image}
                    data-item-name={product.name}
                    data-item-price={product.price}
                  >
                    Add to Cart
                  </button>

              </div>
            )
          })}
        </div>
      </Container>
    </ Layout>
  )
}
